### ISSUE TITLE
How do you set the trigger temperature

### ISSUE THREAD

**Issue by skynet01** [klamann/raspi-poe-mon#1]
Love this thing, soo much better then running it in docker separately, took me 15 seconds to install and run it. Just have one question 

..Is there any way to change the temperature when a fan gets triggered?  Maybe something like 
`raspi-poe-mon run -t56  `

Bonus suggestion!:
- Would be cool to also show if a fan is on an LCD with a "𖣘" icon next to an ip address maybe? 
- Specify check interval? Cause the fan turns on and off every a few seconds for me:

```
Oct 15 17:34:08 pi3b python3[65611]: 2023-10-15 17:34:08,926 [INFO]: CPU temperature at 54.768, turning fan ON
Oct 15 17:34:48 pi3b python3[65611]: 2023-10-15 17:34:48,932 [INFO]: CPU temperature at 47.774, turning fan OFF
Oct 15 17:35:14 pi3b python3[65611]: 2023-10-15 17:35:14,932 [INFO]: CPU temperature at 53.154, turning fan ON
Oct 15 17:35:54 pi3b python3[65611]: 2023-10-15 17:35:54,938 [INFO]: CPU temperature at 47.774, turning fan OFF
Oct 15 17:36:20 pi3b python3[65611]: 2023-10-15 17:36:20,938 [INFO]: CPU temperature at 53.692, turning fan ON
Oct 15 17:36:46 pi3b python3[65611]: 2023-10-15 17:36:46,940 [INFO]: CPU temperature at 47.774, turning fan OFF
Oct 15 17:37:24 pi3b python3[65611]: 2023-10-15 17:37:24,944 [INFO]: CPU temperature at 53.692, turning fan ON
Oct 15 17:37:48 pi3b python3[65611]: 2023-10-15 17:37:48,949 [INFO]: CPU temperature at 47.774, turning fan OFF
Oct 15 17:38:26 pi3b python3[65611]: 2023-10-15 17:38:26,951 [INFO]: CPU temperature at 53.154, turning fan ON
Oct 15 17:38:58 pi3b python3[65611]: 2023-10-15 17:38:58,955 [INFO]: CPU temperature at 47.774, turning fan OFF
```

Thank youz!

**Comment by klamann** [comment]
Thanks for your feedback! Regarding the target temperature, this is already possible:

```
❯ raspi-poe-mon run --help

 Usage: raspi-poe-mon run [OPTIONS]

 start the display and fan controller

╭─ Options ──────────────────────────────────────────────────────────────────────╮
│ --fan-on-temp         FLOAT  [default: 53]                                     │
│ --fan-off-temp        FLOAT  [default: 48]                                     │
│ --frame-time          FLOAT  [default: 2.0]                                    │
│ --help                       Show this message and exit.                       │
╰────────────────────────────────────────────────────────────────────────────────╯
```

So you could e.g. try `raspi-poe-mon run --fan-on-temp 60 --fan-off-temp 50`. If you increase the interval, it will become less likely to turn on and off in short bursts. I wish we could set the fan speed instead, but it seems like all we got is 0% or 100%...

**Comment by klamann** [comment]
> Would be cool to also show if a fan is on an LCD with a "𖣘" icon next to an ip address maybe?

Icons are really hard to draw on a low-res display like this, but if you can find a nice fan icon with max. 12x12 pixels, I may give it a shot :)

**Comment by skynet01** [comment]
... Didn't realize that help command works for each option. 

I figured since that fan icon is a Unicode character it should work. It doesn’t show up properly on the screen?

**Comment by klamann** [comment]
I haven't tested it so far, but had a lot of issues with regular desktop fonts on the small screen. Took me a while to find pixel-perfect fonts for this specific resolution. Here's what the icon would look like at 12x12 pixel when I just scale it down.

![grafik](https://github.com/klamann/raspi-poe-mon/assets/1008877/87ad78a0-e994-4a1c-80a3-2c91752282f4)

And this is greyscale, the OLED display can only show monochrome

**Comment by skynet01** [comment]
Ah i see... thought you could just display a character and the display would take care of the rest. Here is an open-source one that might work:

![fanb-12px](https://github.com/klamann/raspi-poe-mon/assets/8117544/24e7e933-d075-4641-a3bd-c2c9c592e854)
![fan-512px](https://github.com/klamann/raspi-poe-mon/assets/8117544/0c35c855-995c-4238-a8e5-90e1b9f971af)

**Comment by klamann** [comment]
closing this since the question was resolved and the feature request is currently not planned
